version: '3'

services:
  tensorflow:
    build: .
    volumes:
      - ./:/app
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
